**NUMPY Library**

In [249]:
import numpy as np

In [250]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [251]:
#vector addition
print (v1 + v2)

[5 7 9]


In [252]:
#vector subtraction
print(v2 - v1)

[3 3 3]


In [253]:
#vector elementwise multiplication
print(v1 * v2)

[ 4 10 18]


In [254]:
#vector scalar multiplication
print(v1 * 2)

[2 4 6]


In [255]:
# Dot product multiplication
print (v1.dot(v2))

32


In [256]:
##**create a Numpy matrix**
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(m1)  
print("==============================") 
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [257]:
#Matrix addition
print (m1 + m2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [258]:
#Matrix subtraction
print (m2 - m1)

[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]


In [259]:
#Matrix scalar multiplication
print (m1 * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [260]:
#Matrix Elementwise multiplication
print (m1 * m2)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [261]:
#Matrix Dot-product multiplication
print (m1.dot(m2))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [262]:
#Numpy Functions:
print(np.arange(1, 10)) #start, stop
np.arange(1, 10, 2) #start, stop, step

[1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [263]:
np.zeros((3, 3)) #3x3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [264]:
np.ones((2,2)) #2x2 matrix of ones

array([[1., 1.],
       [1., 1.]])

In [265]:
np.linspace(0, 10, 5) #start, stop, number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [266]:
np.eye(3) #3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [267]:
np.random.rand(3, 3) #3x3 matrix of random numbers between 0 and 1

array([[0.62657783, 0.16647599, 0.13330809],
       [0.08586317, 0.4252676 , 0.76824106],
       [0.67085654, 0.09109664, 0.77118676]])

In [268]:
np.random.randn(3, 3) #3x3 matrix of random numbers from standard normal distribution (Guassian distribution)

array([[ 1.57871525,  1.02934173, -2.32543085],
       [-0.86687597, -1.00840442,  0.41526507],
       [-0.59916915,  0.15754818, -0.58407423]])

In [269]:
np.random.randint(1, 20, (3, 3)) #3x3 matrix of random integers between 1 and 20

array([[19,  3,  4],
       [ 8, 10, 13],
       [16,  4,  8]], dtype=int32)

In [270]:
new_array = np.arange(1,26).reshape(5,5) #1D array to 2D array
print(new_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [271]:
new_array.reshape(5,5) #reshape the array to 5x5 matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [272]:
print(new_array.max()) #maximum value in the array
print(new_array.min()) #minimum value in the array 

25
1


In [273]:
print(new_array.argmax()) #index of maximum value in the array
print(new_array.argmin()) #index of minimum value in the array

24
0


In [274]:
new_array.shape #shape of the array

(5, 5)

In [275]:
new_array.dtype #data type of the array

dtype('int64')

**Indexing and Selection**



In [276]:
data=np.arange(0, 11) #create an array with values from 1 to 9  
print (data) #print the array

[ 0  1  2  3  4  5  6  7  8  9 10]


In [277]:
print(data[6]) #access the 6th element of the array
data[0:5] #access the first 5 elements of the array

6


array([0, 1, 2, 3, 4])

In [278]:
data[0:5] = 100 #change the first 5 elements of the array to 100
print(data) #print the modified array

[100 100 100 100 100   5   6   7   8   9  10]


In [279]:
data[:] = 1 #change all elements of the array to 1
print(data) #print the modified array

[1 1 1 1 1 1 1 1 1 1 1]


In [280]:
data_1=data.copy() #create a copy of the array
data_1 = data_1[:10]  # Adjust the size of the array to make it compatible with the desired shape
reshaped_data = data_1.reshape(5, 2)  # Reshape the array to 5x2 matrix
print(reshaped_data)  # Print the reshaped array

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


**2D and 3D slicing:**

In [281]:
two_D=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #create a 2D array
print(two_D) #print the 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [282]:
two_D[0, 2] #access the element at row 0, column 2 of the 2D array

np.int64(3)

In [283]:
print(two_D[:, :]) #access all rows and column of the 2D array
print("=============")
print(two_D[1, :]) #access and print the second row of the 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


In [284]:
print(two_D[1:, 1:]) #access and print the elements from row 1 to end and column 1 to end of the 2D array

[[5 6]
 [8 9]]


In [285]:
print(two_D[two_D > 5]) #access and print the elements of the 2D array that are greater than 5

[6 7 8 9]


In [286]:
np.save('my_array.npy', two_D) #save the array to a file

In [287]:
print(np.sqrt(two_D))       #square root of the elements of the array
print ("==============================")
print(np.std(two_D))       #standard deviation of the elements of the array
print ("==============================")
print(np.var(two_D))       #variance of the elements of the array   
print ("==============================")
print(np.mean(two_D))      #mean of the elements of the array
print ("==============================")
print(np.median(two_D))    #median of the elements of the array
print ("==============================")
print (np.sum(two_D))       #sum of the elements of the array
print ("==============================")
print (np.prod(two_D))      #product of the elements of the array
print ("==============================")
print (np.cumsum(two_D))    #cumulative sum of the elements of the array
print ("==============================")
print (np.cumprod(two_D))   #cumulative product of the elements of the array
print ("==============================")
print (np.diff(two_D))      #difference between consecutive elements of the array
print ("==============================")
print (np.nonzero(two_D))   #indices of non-zero elements of the array


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
2.581988897471611
6.666666666666667
5.0
5.0
45
362880
[ 1  3  6 10 15 21 28 36 45]
[     1      2      6     24    120    720   5040  40320 362880]
[[1 1]
 [1 1]
 [1 1]]
(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


In [288]:
print(np.exp(two_D))      #exponential of the elements of the array
print ("==============================")
print(np.log(two_D))      #natural logarithm of the elements of the array
print ("==============================")
print(np.sin(two_D))       #sine of the elements of the array

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


**Q1= Create a 5X5 matrix where the first diagonal = 1, while the second diagonal = 2, while other values = 3:**

In [289]:
mat1= np.full((5,5),3)
print(mat1) #create a 5x5 matrix of 3's

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [290]:
indeces = list(range(5))
indeces2= indeces[::-1] #reverse the list
print(indeces) #print the original list
print("==============================")
print(indeces2) #print the reversed list

[0, 1, 2, 3, 4]
[4, 3, 2, 1, 0]


In [291]:
mat1[indeces, indeces] = 1 #set the elements of the matrix at the specified indices to 1
print(mat1) #print the modified matrix

[[1 3 3 3 3]
 [3 1 3 3 3]
 [3 3 1 3 3]
 [3 3 3 1 3]
 [3 3 3 3 1]]


In [292]:
mat1[indeces2, indeces] = 2 #set the elements of the matrix at the specified indices to 2
print(mat1) #print the modified matrix

[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 2 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]


***Q2= Consider representing parameters and biases of the following system of linear algebra using matrices and vectors:***


5x1 + 3x2 = 20

3x1 - 6x2 = 10

In [298]:
parameters= np.array([[5, 3],[3, -6]])
biases = np.array([20, 10])

In [299]:
print ("Parameters: ", parameters) #print the parameters
print ("============")
print ("Biases: ", biases) #print the biases

Parameters:  [[ 5  3]
 [ 3 -6]]
Biases:  [20 10]


***Q3= Create two matrices any values you like and stack them vertically:***

In [301]:
mat1 = np.array([[1, 2, 3, 4],
                [4, 5, 6, 7]])
mat2 = np.array([["A", "B", "C", "D"],
                ["S", "O", "N", "M"],
                ["-", "i", "t", "r"]])
mat =np.vstack([mat1, mat2]) #vertical stack of the two matrices
print (mat) #print the stacked matrix

[['1' '2' '3' '4']
 ['4' '5' '6' '7']
 ['A' 'B' 'C' 'D']
 ['S' 'O' 'N' 'M']
 ['-' 'i' 't' 'r']]
