**NUMPY Library**

In [47]:
import numpy as np

In [48]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [49]:
#vector addition
print (v1 + v2)

[5 7 9]


In [50]:
#vector subtraction
print(v2 - v1)

[3 3 3]


In [51]:
#vector elementwise multiplication
print(v1 * v2)

[ 4 10 18]


In [52]:
#vector scalar multiplication
print(v1 * 2)

[2 4 6]


In [53]:
# Dot product multiplication
print (v1.dot(v2))

32


In [54]:
##**create a Numpy matrix**
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(m1)  
print("==============================") 
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [55]:
#Matrix addition
print (m1 + m2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [56]:
#Matrix subtraction
print (m2 - m1)

[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]


In [57]:
#Matrix scalar multiplication
print (m1 * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [58]:
#Matrix Elementwise multiplication
print (m1 * m2)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [59]:
#Matrix Dot-product multiplication
print (m1.dot(m2))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [61]:
#Numpy Functions:
print(np.arange(1, 10)) #start, stop
np.arange(1, 10, 2) #start, stop, step

[1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [62]:
np.zeros((3, 3)) #3x3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.ones((2,2)) #2x2 matrix of ones

array([[1., 1.],
       [1., 1.]])

In [66]:
np.linspace(0, 10, 5) #start, stop, number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [67]:
np.eye(3) #3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.random.rand(3, 3) #3x3 matrix of random numbers between 0 and 1

array([[0.49667418, 0.30031713, 0.8424827 ],
       [0.93723035, 0.93070556, 0.63411412],
       [0.96145036, 0.02955275, 0.80118566]])

In [80]:
np.random.randn(3, 3) #3x3 matrix of random numbers from standard normal distribution (Guassian distribution)

array([[-0.41468952,  1.11593041,  0.11855794],
       [ 0.88100763, -0.36361922,  0.21005161],
       [ 2.07625372,  0.4458204 , -0.91755379]])

In [79]:
np.random.randint(1, 20, (3, 3)) #3x3 matrix of random integers between 1 and 20

array([[ 3, 11,  4],
       [ 2,  3, 14],
       [ 4, 12, 18]], dtype=int32)